// Two kinds of outside party, deliberately kept apart.
//
// SUPPLIERS are businesses we buy from. Their tab is password-gated because the
// card exposes bank details, trade terms and purchase prices — data that is not
// part of the team's daily work. A missing or expired bookkeeping certificate
// blocks PAYMENT, not purchasing.
//
// VENDOR CONTACTS are the named humans behind the third-party systems the
// platform depends on: who to call when an invoice will not issue.
import { SUPPLIER_KIND_IDS } from '@/config/suppliers';
import { L } from '@/lib/localized';

export { SUPPLIER_KIND_IDS };

/** Payment terms a supplier agreement can be on. */
export const PAY_TERM_IDS = ['immediate', 'net30', 'net60', 'net90'];

/** How the supplier is actually paid. */
export const SUPPLIER_PAY_METHOD_IDS = ['transfer', 'cheque'];

/** Legal form of the business. */
export const BUSINESS_TYPE_IDS = ['ltd', 'sole_trader'];

export const DEMO_SUPPLIERS = [
    {
        code: 'S-104',
        name: L('הרבה יבוא צמחי מרפא', 'Herba Medicinal Herb Imports'),
        kind: 'raw_materials',
        biz: '513874902',
        bizType: 'ltd',
        status: 'active',
        contact: L('איתן הרוש', 'Eitan Harush'),
        role: L('מנהל מכירות', 'Sales manager'),
        mobile: '052-330-1147',
        email: 'eitan@herbaimport.co.il',
        office: '03-618-2240',
        orderMail: 'orders@herbaimport.co.il',
        site: 'herbaimport.co.il',
        city: L('חולון', 'Holon'),
        addr: L('המלאכה 14, אזור תעשייה', '14 HaMelacha St, industrial zone'),
        terms: 'net60',
        pay: 'transfer',
        cur: '₪',
        bank: L('לאומי', 'Leumi'),
        branch: '904',
        acct: '38472910',
        payee: L('הרבה יבוא בע״מ', 'Herba Imports Ltd'),
        tradeDisc: 12,
        minOrder: 2500,
        lead: 9,
        coa: true,
        books: { valid: '2026-12-31', ok: true },
        tax: { rate: 0, valid: '2026-12-31', ok: true },
        skus: 21,
        lastReceipt: '2026-07-24',
        spend12: 184300,
        open: 12480,
        since: '2019-04-02',
        suspendedWhy: null,
        suspendedWhen: null,
        notes: L(
            'ספק ראשי לצמחים מיובשים. דורש הזמנה במייל בלבד — לא בטלפון. COA לכל אצווה.',
            'Primary supplier of dried herbs. Orders by email only — never by phone. A COA with every batch.',
        ),
    },
    {
        code: 'S-118',
        name: L('בוטניקה ספקים בע״מ', 'Botanika Suppliers Ltd'),
        kind: 'raw_materials',
        biz: '514029183',
        bizType: 'ltd',
        status: 'active',
        contact: L('מירב סבן', 'Merav Saban'),
        role: L('מנהלת לקוחות', 'Account manager'),
        mobile: '054-771-9930',
        email: 'merav@botanika.co.il',
        office: '09-774-1120',
        orderMail: 'service@botanika.co.il',
        site: 'botanika.co.il',
        city: L('כפר סבא', 'Kfar Saba'),
        addr: L('התעשייה 8', '8 HaTaasiya St'),
        terms: 'net30',
        pay: 'transfer',
        cur: '₪',
        bank: L('הפועלים', 'Hapoalim'),
        branch: '612',
        acct: '119384756',
        payee: L('בוטניקה ספקים בע״מ', 'Botanika Suppliers Ltd'),
        tradeDisc: 8,
        minOrder: 1200,
        lead: 5,
        coa: true,
        books: { valid: '2026-12-31', ok: true },
        tax: { rate: 5, valid: '2026-03-31', ok: false },
        skus: 14,
        lastReceipt: '2026-07-18',
        spend12: 96700,
        open: 0,
        since: '2021-01-19',
        suspendedWhy: null,
        suspendedWhen: null,
        notes: L(
            'אישור ניכוי מס במקור פג — עד לחידוש יש לנכות 5% בכל תשלום.',
            'The withholding-tax certificate has expired — deduct 5% from every payment until it is renewed.',
        ),
    },
    {
        code: 'S-131',
        name: L('כימיפארם — בסיסים ואלכוהול', 'Chemipharm — bases & alcohol'),
        kind: 'bases_alcohol',
        biz: '512930184',
        bizType: 'ltd',
        status: 'active',
        contact: L('ד״ר רון אלימלך', 'Dr. Ron Elimelech'),
        role: L('אחראי רגולציה', 'Regulatory lead'),
        mobile: '050-228-4471',
        email: 'ron@chemipharm.co.il',
        office: '08-943-2210',
        orderMail: 'sales@chemipharm.co.il',
        site: 'chemipharm.co.il',
        city: L('אשדוד', 'Ashdod'),
        addr: L('הגלוון 3, א.ת. הצפוני', '3 HaGalvan St, northern ind. zone'),
        terms: 'net30',
        pay: 'transfer',
        cur: '₪',
        bank: L('מזרחי טפחות', 'Mizrahi Tefahot'),
        branch: '463',
        acct: '284019374',
        payee: L('כימיפארם בע״מ', 'Chemipharm Ltd'),
        tradeDisc: 5,
        minOrder: 900,
        lead: 4,
        coa: true,
        books: { valid: '2026-12-31', ok: true },
        tax: { rate: 0, valid: '2026-12-31', ok: true },
        skus: 9,
        lastReceipt: '2026-07-11',
        spend12: 71200,
        open: 4390,
        since: '2020-08-11',
        suspendedWhy: null,
        suspendedWhen: null,
        notes: L(
            'אלכוהול 96% — נדרש היתר רכש בתוקף. משלוח בטמפרטורה מבוקרת.',
            '96% alcohol — a valid purchase permit is required. Temperature-controlled delivery.',
        ),
    },
    {
        code: 'S-142',
        name: L('גלסקו אריזות זכוכית', 'Glasco Glass Packaging'),
        kind: 'packaging',
        biz: '029384756',
        bizType: 'sole_trader',
        status: 'active',
        contact: L('שמעון ביטון', 'Shimon Biton'),
        role: L('בעל העסק', 'Owner'),
        mobile: '052-994-2018',
        email: 'shimon@glasco.co.il',
        office: null,
        orderMail: 'shimon@glasco.co.il',
        site: null,
        city: L('ראשון לציון', 'Rishon LeZion'),
        addr: L('יוסף ספיר 22', '22 Yosef Sapir St'),
        terms: 'immediate',
        pay: 'transfer',
        cur: '₪',
        bank: L('דיסקונט', 'Discount'),
        branch: '077',
        acct: '740192837',
        payee: L('שמעון ביטון', 'Shimon Biton'),
        tradeDisc: 0,
        minOrder: 400,
        lead: 3,
        coa: false,
        books: { valid: '2026-12-31', ok: true },
        tax: { rate: 30, valid: null, ok: false },
        skus: 11,
        lastReceipt: '2026-07-21',
        spend12: 38400,
        open: 0,
        since: '2022-05-30',
        suspendedWhy: null,
        suspendedWhen: null,
        notes: L(
            'עוסק מורשה ללא אישור פטור — ניכוי 30% במקור עד להצגת אישור.',
            'Sole trader with no exemption certificate — withhold 30% at source until one is produced.',
        ),
    },
    {
        code: 'S-155',
        name: L('נוטרה-לאב מוצרי מדף', 'Nutra-Lab Shelf Products'),
        kind: 'raw_materials',
        biz: '515102938',
        bizType: 'ltd',
        status: 'active',
        contact: L('ליאור אדרי', 'Lior Edri'),
        role: L('מנהל מסחרי', 'Commercial manager'),
        mobile: '053-660-7712',
        email: 'lior@nutralab.co.il',
        office: '04-877-3320',
        orderMail: 'orders@nutralab.co.il',
        site: 'nutralab.co.il',
        city: L('יקנעם', 'Yokneam'),
        addr: L('המדע 5', '5 HaMada St'),
        terms: 'net60',
        pay: 'cheque',
        cur: '₪',
        bank: L('לאומי', 'Leumi'),
        branch: '812',
        acct: '502837465',
        payee: L('נוטרה-לאב בע״מ', 'Nutra-Lab Ltd'),
        tradeDisc: 22,
        minOrder: 3000,
        lead: 7,
        coa: true,
        books: { valid: '2026-12-31', ok: true },
        tax: { rate: 0, valid: '2027-03-31', ok: true },
        skus: 18,
        lastReceipt: '2026-07-27',
        spend12: 142900,
        open: 21600,
        since: '2018-11-04',
        suspendedWhy: null,
        suspendedWhen: null,
        notes: L(
            'מוצרי מדף במיתוג טריפוליום. תמחור לפי מדרגות כמות — מעודכן ברשימת המחירים.',
            'Shelf products under the Trifolium brand. Priced on quantity tiers — kept in the price lists.',
        ),
    },
    {
        code: 'S-163',
        name: L('תפוז שליחויות', 'Tapuz Couriers'),
        kind: 'logistics',
        biz: '514772019',
        bizType: 'ltd',
        status: 'active',
        contact: L('איציק פרץ', 'Itzik Peretz'),
        role: L('מנהל תפעול', 'Operations manager'),
        mobile: '052-441-3374',
        email: 'izik@tapuz-delivery.co.il',
        office: '08-991-3374',
        orderMail: 'ops@tapuz-delivery.co.il',
        site: 'tapuz-delivery.co.il',
        city: L('לוד', 'Lod'),
        addr: L('שדרות ירושלים 40', '40 Jerusalem Blvd'),
        terms: 'net30',
        pay: 'transfer',
        cur: '₪',
        bank: L('הפועלים', 'Hapoalim'),
        branch: '533',
        acct: '918273645',
        payee: L('תפוז שליחויות בע״מ', 'Tapuz Couriers Ltd'),
        tradeDisc: 0,
        minOrder: 0,
        lead: 1,
        coa: false,
        books: { valid: '2026-12-31', ok: true },
        tax: { rate: 0, valid: '2026-12-31', ok: true },
        skus: 0,
        lastReceipt: null,
        spend12: 64800,
        open: 3120,
        since: '2021-06-15',
        suspendedWhy: null,
        suspendedWhen: null,
        notes: L(
            'חיוב חודשי מרוכז לפי מספר משלוחים. קוד ספק T במסך המשלוחים.',
            'Billed monthly in one invoice by shipment count. Courier code T on the deliveries screen.',
        ),
    },
    {
        code: 'S-170',
        name: L('עדן תמציות', 'Eden Extracts'),
        kind: 'raw_materials',
        biz: '513002948',
        bizType: 'ltd',
        status: 'suspended',
        contact: L('נטלי כרמי', 'Natalie Carmi'),
        role: L('מנהלת מכירות', 'Sales manager'),
        mobile: '058-330-9914',
        email: 'natalie@edenext.co.il',
        office: '03-550-1180',
        orderMail: 'natalie@edenext.co.il',
        site: null,
        city: L('פתח תקווה', 'Petah Tikva'),
        addr: L('הסיבים 19', '19 HaSivim St'),
        terms: 'net30',
        pay: 'transfer',
        cur: '$',
        bank: L('לאומי', 'Leumi'),
        branch: '710',
        acct: '664201938',
        payee: L('עדן תמציות בע״מ', 'Eden Extracts Ltd'),
        tradeDisc: 10,
        minOrder: 5000,
        lead: 21,
        coa: false,
        books: { valid: '2025-12-31', ok: false },
        tax: { rate: 30, valid: null, ok: false },
        skus: 4,
        lastReceipt: '2026-02-02',
        spend12: 8900,
        open: 0,
        since: '2023-09-21',
        suspendedWhy: L(
            'שתי אצוות ללא COA + אישור ניהול ספרים פג',
            'Two batches without a COA + an expired bookkeeping certificate',
        ),
        suspendedWhen: '2026-03-14',
        notes: L(
            'מושהה לרכש. אין להזמין עד להצגת COA ואישור ניהול ספרים בתוקף.',
            'Suspended for purchasing. Do not order until a COA and a valid bookkeeping certificate are produced.',
        ),
    },
];

/**
 * Named contacts at the third-party systems the platform depends on. Who to
 * call, and what they will ask for when you do.
 */
export const DEMO_VENDOR_CONTACTS = [
    {
        id: 'v1',
        system: L('Green Invoice — מסמכי מס', 'Green Invoice — tax documents'),
        icon: 'file_text',
        contact: L('דורון אשכנזי', 'Doron Ashkenazi'),
        role: L('מנהל לקוחות עסקיים', 'Business account manager'),
        phone: '03-644-2081',
        notes: L(
            'הפקת חשבוניות מס קבלה ומספרי הקצאה. בכשל הפקה — פנייה עם מספר הבקשה מלוג המסמכים. SLA-4H.',
            'Issues tax invoices/receipts and allocation numbers. On a failure, call with the request id from the document log. 4-hour SLA.',
        ),
    },
    {
        id: 'v2',
        system: L('InforU — WhatsApp ו-SMS', 'InforU — WhatsApp & SMS'),
        icon: 'whatsapp',
        contact: L('שירה בן-חמו', 'Shira Ben-Hamo'),
        role: L('מנהלת לקוח', 'Account manager'),
        phone: '073-374-1120',
        notes: L(
            'אישור תבניות WhatsApp מולה מראש — 2–3 ימי עסקים. תקלות שליחה: מוקד 24/7.',
            'WhatsApp templates are approved through her in advance — 2–3 business days. Send failures: 24/7 desk.',
        ),
    },
    {
        id: 'v3',
        system: L('תפוז שליחויות', 'Tapuz Couriers'),
        icon: 'truck',
        contact: L('איציק פרץ', 'Itzik Peretz'),
        role: L('מנהל תפעול', 'Operations manager'),
        phone: '08-991-3374',
        notes: L(
            'קוד ספק T. חסימת איסופים אחרי 15:00. אין עדיין אינטגרציית API — עדכון מעקב ידני.',
            'Courier code T. No pickups booked after 15:00. No API integration yet — tracking numbers are entered by hand.',
        ),
    },
    {
        id: 'v4',
        system: L('סליקת אשראי', 'Card processing'),
        icon: 'card',
        contact: L('נועה שרעבי', 'Noa Sharabi'),
        role: L('תמיכה טכנית', 'Technical support'),
        phone: '03-763-9915',
        notes: L(
            'החזרים מעל ₪1,000 דורשים אישור בכתב. דוח התאמה יומי מגיע ב-02:00.',
            'Refunds over ₪1,000 need written approval. The daily reconciliation report arrives at 02:00.',
        ),
    },
    {
        id: 'v5',
        system: L('אחסון ותשתית', 'Hosting & infrastructure'),
        icon: 'layers',
        contact: L('רן אליהו', 'Ran Eliyahu'),
        role: L('DevOps חיצוני', 'External DevOps'),
        phone: '052-880-4417',
        notes: L(
            'איש הקשר לשחזור גיבוי ולתעודות SSL. זמין גם מחוץ לשעות למקרי השבתה.',
            'The contact for backup restores and SSL certificates. Reachable out of hours for an outage.',
        ),
    },
];

/**
 * Why the supplier tab is gated, and how long an unlock lasts. Copy for the
 * dialog lives in the locale catalog; these are the facts it states.
 */
export const SUPPLIER_GATE = { unlockUntil: 'page_exit_or_manual_lock' };
